### PR TITLE
Delete data directory

### PR DESCRIPTION
**Pull request by BichengYing**

### CODE REVIEW

**Comment by ZidongLiu** [comment]
If we delete data for shakespeare, the branch logics related to it should also be deleted.
image

**Review by ZidongLiu — CHANGES_REQUESTED** [review]
If we delete data for shakespeare, the branch logics related to it should also be deleted.

image

**Comment by BichengYing** [comment]
> If we delete data for shakespeare, the branch logics related to it should also be deleted.
> 
> image

No. Data should not be checked into the github repo, it should be existed in the local directory.  We have add `data/*` into the gitignore file. Somehow this file missed it.

**Comment by ZidongLiu** [comment]
> > If we delete data for shakespeare, the branch logics related to it should also be deleted.
> > image
> 
> No. Data should not be checked into the github repo. It should exists in the local directory only. We have add `data/*` into the gitignore file. Somehow this file missed it. Screenshot 2024-09-03 at 11 31 37 AM

Code can work depends heavily on the data we added to repo. A new clone of this repo after we remove the data, code won't work when 'dataset=shakespeare'.

Or if we need to provide a way to download the shakespeare data when it's not available locally. just like

**Comment by BichengYing** [comment]
> Code can work depends heavily on the data we added to repo. A new clone of this repo after we remove the data, code won't work when 'dataset=shakespeare'.
> 
> Or if we need to provide a way to download the shakespeare data when it's not available locally. just like other datasets

Good point, i remember now. `shakespeare` dataset is hard to download now. Hmm, it is ugly to have this single dataset in the repo.... Hmmm

**Comment by ZidongLiu** [comment]
will not be implemented in near future. probably will host shakespeare data in github, need further discussion

**Pull request closed without merging**
